[tool.poetry]
name = "GDNeural_brain_games"
version = "0.1.0"
description = ""
authors = ["skip"]
packages = [
  { include = "brain_games" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.4"
wemake-python-styleguide = "^0.8.1"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
brain-even = "brain_games.scripts.brain_even:second"
brain-calc = "brain_games.scripts.brain_calc:third"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
